[package]
name = "efrust-lsp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

description = "Language server para el lenguaje de modelos EFM (.model)"

[[bin]]
name = "efrust-lsp"
path = "src/main.rs"

[dependencies]
efrust-lang = { workspace = true }
efrust-core = { workspace = true }
tower-lsp = "0.20"
tokio = { workspace = true, features = ["io-std", "rt-multi-thread", "macros"] }
dashmap = "6"
serde_json = { workspace = true }
