-- Sync script generated by molde
-- Source: sqlite:/tmp/src.db
-- Target: sqlite:/tmp/tgt.db
-- Additive: does not drop or alter anything existing in the target.

BEGIN;

-- ===== NEW TABLES =====
CREATE TABLE IF NOT EXISTS Invoice (Id INTEGER PRIMARY KEY, CustomerId INTEGER, Total REAL);

-- ===== NEW COLUMNS =====
ALTER TABLE "Customer" ADD COLUMN "Phone" TEXT;

-- ===== INDEXES =====
CREATE INDEX IF NOT EXISTS ix_inv_cust ON Invoice(CustomerId);

COMMIT;
