//! # efrust-providers
//!
//! Generación de SQL específica por motor. Define el trait [`SqlGenerator`] y
//! sus implementaciones. En Fase 0 hay dos: SQLite (tests rápidos) y PostgreSQL.
//! SQL Server y MySQL llegan en fase posterior siguiendo el mismo trait.

pub mod generator;
pub mod mysql;
pub mod postgres;
pub mod sqlite;
pub mod sqlserver;

pub use generator::{ProviderError, SqlGenerator};
pub use mysql::MySqlGenerator;
pub use postgres::PostgresGenerator;
pub use sqlite::SqliteGenerator;
pub use sqlserver::SqlServerGenerator;

/// Motores soportados.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Provider {
    Sqlite,
    Postgres,
    MySql,
    /// SQL Server: apply y scaffold vía tiberius (driver TDS).
    SqlServer,
}

impl Provider {
    /// Resuelve un provider desde una cadena (`--provider postgres`).
    pub fn parse(s: &str) -> Option<Self> {
        match s.to_ascii_lowercase().as_str() {
            "sqlite" => Some(Self::Sqlite),
            "postgres" | "postgresql" | "npgsql" => Some(Self::Postgres),
            "mysql" | "mariadb" => Some(Self::MySql),
            "sqlserver" | "mssql" => Some(Self::SqlServer),
            _ => None,
        }
    }

    /// Infiere el provider desde el esquema de una cadena de conexión sqlx.
    pub fn from_url(url: &str) -> Option<Self> {
        let lower = url.trim().to_ascii_lowercase();
        if lower.starts_with("postgres://") || lower.starts_with("postgresql://") {
            Some(Self::Postgres)
        } else if lower.starts_with("sqlite:") {
            Some(Self::Sqlite)
        } else if lower.starts_with("mysql://") || lower.starts_with("mariadb://") {
            Some(Self::MySql)
        } else if lower.starts_with("sqlserver://") || lower.starts_with("mssql://") {
            Some(Self::SqlServer)
        } else {
            None
        }
    }

    /// Devuelve el generador correspondiente como objeto de trait.
    pub fn generator(self) -> Box<dyn SqlGenerator> {
        match self {
            Self::Sqlite => Box::new(SqliteGenerator::new()),
            Self::Postgres => Box::new(PostgresGenerator::new()),
            Self::MySql => Box::new(MySqlGenerator::new()),
            Self::SqlServer => Box::new(SqlServerGenerator::new()),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use efrust_core::diff::Operation;
    use efrust_core::model::{Column, PrimaryKey, Table};

    fn id_col() -> Column {
        Column {
            name: "Id".into(),
            store_type: None,
            clr_type: Some("System.Int32".into()),
            is_nullable: false,
            is_identity: true,
            max_length: None,
            precision: None,
            scale: None,
            default_value_sql: None,
            computed_sql: None,
            computed_stored: false,
            collation: None,
            comment: None,
        }
    }

    fn name_col() -> Column {
        Column {
            name: "Name".into(),
            store_type: None,
            clr_type: Some("System.String".into()),
            is_nullable: false,
            is_identity: false,
            max_length: Some(200),
            precision: None,
            scale: None,
            default_value_sql: None,
            computed_sql: None,
            computed_stored: false,
            collation: None,
            comment: None,
        }
    }

    fn customer() -> Table {
        Table {
            name: "Customer".into(),
            schema: None,
            clr_type: Some("App.Models.Customer".into()),
            comment: None,
            columns: vec![id_col(), name_col()],
            primary_key: Some(PrimaryKey {
                name: "PK_Customer".into(),
                columns: vec!["Id".into()],
            }),
            foreign_keys: vec![],
            indexes: vec![],
            triggers: vec![],
            seed_data: vec![],
        }
    }

    #[test]
    fn postgres_create_table() {
        let gen = PostgresGenerator::new();
        let sql = gen
            .emit(&Operation::CreateTable { table: customer() })
            .unwrap();
        let joined = sql.join("\n");
        assert!(joined.contains("CREATE TABLE \"Customer\""));
        assert!(joined.contains("GENERATED BY DEFAULT AS IDENTITY"));
        assert!(joined.contains("character varying(200)"));
        assert!(joined.contains("PRIMARY KEY"));
    }

    #[test]
    fn sqlite_create_table() {
        let gen = SqliteGenerator::new();
        let sql = gen
            .emit(&Operation::CreateTable { table: customer() })
            .unwrap();
        let joined = sql.join("\n");
        assert!(joined.contains("CREATE TABLE \"Customer\""));
        assert!(joined.contains("PRIMARY KEY AUTOINCREMENT"));
        assert!(joined.contains("\"Name\" TEXT NOT NULL"));
    }

    #[test]
    fn sqlite_alter_column_se_difiere_al_rebuild() {
        // SQLite ya no falla en ALTER COLUMN: lo omite (no-op) porque el cambio
        // se materializa con la RebuildTable que emite `diff()`.
        let gen = SqliteGenerator::new();
        let op = Operation::AlterColumn {
            schema: None,
            table: "Customer".into(),
            new: name_col(),
            old: name_col(),
        };
        assert!(gen.emit(&op).unwrap().is_empty());
    }

    fn fk_op() -> Operation {
        use efrust_core::model::{ForeignKey, ReferentialAction};
        Operation::AddForeignKey {
            schema: None,
            table: "Order".into(),
            foreign_key: ForeignKey {
                name: "FK_Order_Customer".into(),
                columns: vec!["CustomerId".into()],
                principal_table: "Customer".into(),
                principal_schema: None,
                principal_columns: vec!["Id".into()],
                on_delete: ReferentialAction::Cascade,
            },
        }
    }

    fn index_op() -> Operation {
        use efrust_core::model::Index;
        Operation::CreateIndex {
            schema: None,
            table: "Order".into(),
            index: Index {
                name: "IX_Order_CustomerId".into(),
                columns: vec!["CustomerId".into()],
                is_unique: true,
                filter: None,
                method: None,
                operators: vec![],
                expression: None,
            },
        }
    }

    #[test]
    fn postgres_foreign_key_e_indice() {
        let gen = PostgresGenerator::new();
        let fk = gen.emit(&fk_op()).unwrap().join("\n");
        assert!(fk.contains(
            "ALTER TABLE \"Order\" ADD CONSTRAINT \"FK_Order_Customer\" \
             FOREIGN KEY (\"CustomerId\") REFERENCES \"Customer\" (\"Id\") ON DELETE CASCADE;"
        ));
        let ix = gen.emit(&index_op()).unwrap().join("\n");
        assert!(ix.contains("CREATE UNIQUE INDEX \"IX_Order_CustomerId\" ON \"Order\" (\"CustomerId\");"));
    }

    #[test]
    fn postgres_indice_vectorial_hnsw_con_operator_class() {
        use efrust_core::model::Index;
        let op = Operation::CreateIndex {
            schema: None,
            table: "documents".into(),
            index: Index {
                name: "ix_docs_embedding".into(),
                columns: vec!["embedding".into()],
                is_unique: false,
                filter: None,
                method: Some("hnsw".into()),
                operators: vec!["vector_cosine_ops".into()],
                expression: None,
            },
        };
        let sql = PostgresGenerator::new().emit(&op).unwrap().join("\n");
        assert!(sql.contains(
            "CREATE INDEX \"ix_docs_embedding\" ON \"documents\" USING hnsw (\"embedding\" vector_cosine_ops);"
        ), "got: {sql}");
    }

    #[test]
    fn postgres_indice_gin_por_expresion() {
        use efrust_core::model::Index;
        let op = Operation::CreateIndex {
            schema: None,
            table: "documents".into(),
            index: Index {
                name: "ix_docs_fts".into(),
                columns: vec![],
                is_unique: false,
                filter: None,
                method: Some("gin".into()),
                operators: vec![],
                expression: Some("to_tsvector('english'::regconfig, body)".into()),
            },
        };
        let sql = PostgresGenerator::new().emit(&op).unwrap().join("\n");
        assert!(sql.contains(
            "CREATE INDEX \"ix_docs_fts\" ON \"documents\" USING gin (to_tsvector('english'::regconfig, body));"
        ), "got: {sql}");
    }

    #[test]
    fn postgres_funcion_y_trigger_emiten_definition_crudo() {
        use efrust_core::model::{DbFunction, Trigger, TriggerEvent, TriggerTiming};
        let gen = PostgresGenerator::new();
        let f = gen
            .emit(&Operation::CreateFunction {
                function: DbFunction {
                    name: "normalize_body".into(),
                    schema: Some("public".into()),
                    definition: "CREATE FUNCTION normalize_body() RETURNS trigger AS $$ BEGIN RETURN NEW; END $$ LANGUAGE plpgsql".into(),
                },
            })
            .unwrap()
            .join("\n");
        assert!(f.contains("CREATE FUNCTION normalize_body()"));

        let t = gen
            .emit(&Operation::CreateTrigger {
                schema: None,
                table: "documents".into(),
                trigger: Trigger {
                    name: "trg_norm".into(),
                    table: "documents".into(),
                    schema: None,
                    timing: TriggerTiming::Before,
                    events: vec![TriggerEvent::Insert],
                    function: Some("normalize_body".into()),
                    definition: "CREATE TRIGGER trg_norm BEFORE INSERT ON documents FOR EACH ROW EXECUTE FUNCTION normalize_body()".into(),
                },
            })
            .unwrap()
            .join("\n");
        assert!(t.contains("CREATE TRIGGER trg_norm BEFORE INSERT ON documents"));

        let drop = gen
            .emit(&Operation::DropTrigger { schema: None, table: "documents".into(), name: "trg_norm".into() })
            .unwrap()
            .join("\n");
        assert!(drop.contains("DROP TRIGGER IF EXISTS \"trg_norm\" ON \"documents\";"));
    }

    #[test]
    fn postgres_ensure_extension() {
        let gen = PostgresGenerator::new();
        let sql = gen
            .emit(&Operation::EnsureExtension { name: "vector".into() })
            .unwrap()
            .join("\n");
        assert_eq!(sql, "CREATE EXTENSION IF NOT EXISTS \"vector\";");
        // SQLite la omite con aviso (sin SQL).
        assert!(SqliteGenerator::new()
            .emit(&Operation::EnsureExtension { name: "vector".into() })
            .unwrap()
            .is_empty());
    }

    #[test]
    fn sqlite_omite_funciones_y_triggers() {
        use efrust_core::model::DbFunction;
        let gen = SqliteGenerator::new();
        let out = gen
            .emit(&Operation::CreateFunction {
                function: DbFunction { name: "f".into(), schema: None, definition: "...".into() },
            })
            .unwrap();
        assert!(out.is_empty(), "SQLite omite funciones con aviso");
    }

    #[test]
    fn sqlite_rebuild_table_secuencia() {
        use efrust_core::model::PrimaryKey;
        let mut t = customer();
        t.name = "Order".into();
        t.primary_key = Some(PrimaryKey { name: "PK_Order".into(), columns: vec!["Id".into()] });
        let op = Operation::RebuildTable {
            table: t,
            copy_columns: vec!["Id".into(), "Name".into()],
        };
        let sql = SqliteGenerator::new().emit(&op).unwrap();
        let joined = sql.join("\n");
        assert!(joined.contains("CREATE TABLE \"Order_efrust_new\""), "got: {joined}");
        assert!(joined.contains("INSERT INTO \"Order_efrust_new\" (\"Id\", \"Name\") SELECT \"Id\", \"Name\" FROM \"Order\";"));
        assert!(joined.contains("DROP TABLE \"Order\";"));
        assert!(joined.contains("ALTER TABLE \"Order_efrust_new\" RENAME TO \"Order\";"));

        // Motores capaces: RebuildTable es no-op (usan ALTER granular).
        assert!(PostgresGenerator::new().emit(&op).unwrap().is_empty());
        assert!(MySqlGenerator::new().emit(&op).unwrap().is_empty());
    }

    #[test]
    fn sqlserver_columna_computada_persisted() {
        use efrust_core::model::Column;
        let col = Column {
            name: "FullName".into(),
            store_type: None,
            clr_type: Some("System.String".into()),
            is_nullable: false,
            is_identity: false,
            max_length: None,
            precision: None,
            scale: None,
            default_value_sql: None,
            computed_sql: Some("([First]+' '+[Last])".into()),
            computed_stored: true,
            collation: None,
            comment: None,
        };
        let sql = SqlServerGenerator::new()
            .emit(&Operation::AddColumn { schema: None, table: "People".into(), column: col })
            .unwrap()
            .join("\n");
        assert!(sql.contains("[FullName] AS ([First]+' '+[Last]) PERSISTED NOT NULL"), "got: {sql}");
    }

    #[test]
    fn datos_sembrados_insert_update_delete() {
        use serde_json::json;
        let mut row = std::collections::BTreeMap::new();
        row.insert("Id".to_string(), json!(1));
        row.insert("Name".to_string(), json!("O'Brien"));
        row.insert("Active".to_string(), json!(true));

        let ins = PostgresGenerator::new()
            .emit(&Operation::InsertData { schema: None, table: "Cat".into(), row: row.clone() })
            .unwrap()
            .join("\n");
        // Orden de columnas alfabético (BTreeMap), bool de Postgres = TRUE, escape de comillas.
        assert_eq!(
            ins,
            "INSERT INTO \"Cat\" (\"Active\", \"Id\", \"Name\") VALUES (TRUE, 1, 'O''Brien');"
        );
        // En MySQL el bool es 1/0.
        let ins_my = MySqlGenerator::new()
            .emit(&Operation::InsertData { schema: None, table: "Cat".into(), row })
            .unwrap()
            .join("\n");
        assert!(ins_my.contains("VALUES (1, 1, 'O''Brien');"), "got: {ins_my}");

        let mut key = std::collections::BTreeMap::new();
        key.insert("Id".to_string(), json!(1));
        let del = SqliteGenerator::new()
            .emit(&Operation::DeleteData { schema: None, table: "Cat".into(), key: key.clone() })
            .unwrap()
            .join("\n");
        assert_eq!(del, "DELETE FROM \"Cat\" WHERE \"Id\" = 1;");

        let mut vals = std::collections::BTreeMap::new();
        vals.insert("Name".to_string(), json!("New"));
        let upd = SqliteGenerator::new()
            .emit(&Operation::UpdateData { schema: None, table: "Cat".into(), key, values: vals })
            .unwrap()
            .join("\n");
        assert_eq!(upd, "UPDATE \"Cat\" SET \"Name\" = 'New' WHERE \"Id\" = 1;");
    }

    #[test]
    fn raw_sql_verbatim_en_todos_los_motores() {
        let op = Operation::RawSql { sql: "CREATE FULLTEXT CATALOG [ft];".into() };
        for sql in [
            PostgresGenerator::new().emit(&op).unwrap().join(""),
            MySqlGenerator::new().emit(&op).unwrap().join(""),
            SqliteGenerator::new().emit(&op).unwrap().join(""),
            SqlServerGenerator::new().emit(&op).unwrap().join(""),
        ] {
            assert_eq!(sql, "CREATE FULLTEXT CATALOG [ft];");
        }
    }

    #[test]
    fn mysql_create_table_fk_indice() {
        let gen = MySqlGenerator::new();
        let create = gen.emit(&Operation::CreateTable { table: customer() }).unwrap().join("\n");
        assert!(create.contains("CREATE TABLE `Customer`"));
        assert!(create.contains("`Id` int NOT NULL AUTO_INCREMENT"));
        assert!(create.contains("`Name` varchar(200) NOT NULL"));
        assert!(create.contains("PRIMARY KEY (`Id`)"));

        let fk = gen.emit(&fk_op()).unwrap().join("\n");
        assert!(fk.contains(
            "ALTER TABLE `Order` ADD CONSTRAINT `FK_Order_Customer` \
             FOREIGN KEY (`CustomerId`) REFERENCES `Customer` (`Id`) ON DELETE CASCADE;"
        ));
        let ix = gen.emit(&index_op()).unwrap().join("\n");
        assert!(ix.contains("CREATE UNIQUE INDEX `IX_Order_CustomerId` ON `Order` (`CustomerId`);"));
    }

    #[test]
    fn mysql_fulltext_index_y_columna_generada() {
        use efrust_core::model::{Column, Index};
        let gen = MySqlGenerator::new();
        // FULLTEXT index.
        let op = Operation::CreateIndex {
            schema: None,
            table: "documents".into(),
            index: Index {
                name: "ft_body".into(),
                columns: vec!["body".into()],
                is_unique: false,
                filter: None,
                method: Some("fulltext".into()),
                operators: vec![],
                expression: None,
            },
        };
        let sql = gen.emit(&op).unwrap().join("\n");
        assert!(sql.contains("CREATE FULLTEXT INDEX `ft_body` ON `documents` (`body`);"), "got: {sql}");

        // Columna generada STORED.
        let col = Column {
            name: "slug".into(),
            store_type: Some("varchar(255)".into()),
            clr_type: Some("System.String".into()),
            is_nullable: false,
            is_identity: false,
            max_length: Some(255),
            precision: None,
            scale: None,
            default_value_sql: None,
            computed_sql: Some("lower(`title`)".into()),
            computed_stored: true,
            collation: None,
            comment: None,
        };
        let add = gen
            .emit(&Operation::AddColumn { schema: None, table: "documents".into(), column: col })
            .unwrap()
            .join("\n");
        assert!(add.contains("GENERATED ALWAYS AS (lower(`title`)) STORED"), "got: {add}");
    }

    #[test]
    fn sqlite_indice_si_fk_inline_en_create_table() {
        let gen = SqliteGenerator::new();
        // El índice se genera.
        let ix = gen.emit(&index_op()).unwrap().join("\n");
        assert!(ix.contains("CREATE UNIQUE INDEX \"IX_Order_CustomerId\" ON \"Order\" (\"CustomerId\");"));
        // La FK por ALTER se omite (sin sentencias): SQLite la declara inline.
        let fk = gen.emit(&fk_op()).unwrap();
        assert!(fk.is_empty(), "SQLite omite AddForeignKey (va inline en CREATE TABLE)");
    }

    #[test]
    fn sqlite_create_table_incluye_fk_inline() {
        use efrust_core::model::{ForeignKey, ReferentialAction};
        let mut order = customer();
        order.name = "Order".into();
        order.foreign_keys.push(ForeignKey {
            name: "FK_Order_Customer".into(),
            columns: vec!["Name".into()],
            principal_table: "Customer".into(),
            principal_schema: None,
            principal_columns: vec!["Id".into()],
            on_delete: ReferentialAction::Cascade,
        });
        let sql = SqliteGenerator::new()
            .emit(&Operation::CreateTable { table: order })
            .unwrap()
            .join("\n");
        assert!(sql.contains(
            "CONSTRAINT \"FK_Order_Customer\" FOREIGN KEY (\"Name\") \
             REFERENCES \"Customer\" (\"Id\") ON DELETE CASCADE"
        ));
    }

    #[test]
    fn sqlserver_genera_tsql() {
        let gen = SqlServerGenerator::new();
        let create = gen.emit(&Operation::CreateTable { table: customer() }).unwrap().join("\n");
        assert!(create.contains("CREATE TABLE [Customer]"));
        assert!(create.contains("[Id] int NOT NULL IDENTITY(1,1)"));
        assert!(create.contains("[Name] nvarchar(200) NOT NULL"));
        assert!(create.contains("CONSTRAINT [PK_Customer] PRIMARY KEY ([Id])"));

        let fk = gen.emit(&fk_op()).unwrap().join("\n");
        assert!(fk.contains(
            "ALTER TABLE [Order] ADD CONSTRAINT [FK_Order_Customer] \
             FOREIGN KEY ([CustomerId]) REFERENCES [Customer] ([Id]) ON DELETE CASCADE;"
        ));
    }
}
