//! # efrust-providers
//!
//! Generación de SQL específica por motor. Define el trait [`SqlGenerator`] y
//! sus implementaciones. En Fase 0 hay dos: SQLite (tests rápidos) y PostgreSQL.
//! SQL Server y MySQL llegan en fase posterior siguiendo el mismo trait.

pub mod generator;
pub mod mysql;
pub mod postgres;
pub mod sqlite;
pub mod sqlserver;

pub use generator::{ProviderError, SqlGenerator};
pub use mysql::MySqlGenerator;
pub use postgres::PostgresGenerator;
pub use sqlite::SqliteGenerator;
pub use sqlserver::SqlServerGenerator;

/// Motores soportados.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Provider {
    Sqlite,
    Postgres,
    MySql,
    /// SQL Server: apply y scaffold vía tiberius (driver TDS).
    SqlServer,
}

impl Provider {
    /// Resuelve un provider desde una cadena (`--provider postgres`).
    pub fn parse(s: &str) -> Option<Self> {
        match s.to_ascii_lowercase().as_str() {
            "sqlite" => Some(Self::Sqlite),
            "postgres" | "postgresql" | "npgsql" => Some(Self::Postgres),
            "mysql" | "mariadb" => Some(Self::MySql),
            "sqlserver" | "mssql" => Some(Self::SqlServer),
            _ => None,
        }
    }

    /// Infiere el provider desde el esquema de una cadena de conexión sqlx.
    pub fn from_url(url: &str) -> Option<Self> {
        let lower = url.trim().to_ascii_lowercase();
        if lower.starts_with("postgres://") || lower.starts_with("postgresql://") {
            Some(Self::Postgres)
        } else if lower.starts_with("sqlite:") {
            Some(Self::Sqlite)
        } else if lower.starts_with("mysql://") || lower.starts_with("mariadb://") {
            Some(Self::MySql)
        } else if lower.starts_with("sqlserver://") || lower.starts_with("mssql://") {
            Some(Self::SqlServer)
        } else {
            None
        }
    }

    /// Devuelve el generador correspondiente como objeto de trait.
    pub fn generator(self) -> Box<dyn SqlGenerator> {
        match self {
            Self::Sqlite => Box::new(SqliteGenerator::new()),
            Self::Postgres => Box::new(PostgresGenerator::new()),
            Self::MySql => Box::new(MySqlGenerator::new()),
            Self::SqlServer => Box::new(SqlServerGenerator::new()),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use efrust_core::diff::Operation;
    use efrust_core::model::{Column, PrimaryKey, Table};

    fn id_col() -> Column {
        Column {
            name: "Id".into(),
            store_type: None,
            clr_type: Some("System.Int32".into()),
            is_nullable: false,
            is_identity: true,
            max_length: None,
            precision: None,
            scale: None,
            default_value_sql: None,
            computed_sql: None,
            computed_stored: false,
            collation: None,
            comment: None,
        }
    }

    fn name_col() -> Column {
        Column {
            name: "Name".into(),
            store_type: None,
            clr_type: Some("System.String".into()),
            is_nullable: false,
            is_identity: false,
            max_length: Some(200),
            precision: None,
            scale: None,
            default_value_sql: None,
            computed_sql: None,
            computed_stored: false,
            collation: None,
            comment: None,
        }
    }

    fn customer() -> Table {
        Table {
            name: "Customer".into(),
            schema: None,
            clr_type: Some("App.Models.Customer".into()),
            comment: None,
            columns: vec![id_col(), name_col()],
            primary_key: Some(PrimaryKey {
                name: "PK_Customer".into(),
                columns: vec!["Id".into()],
            }),
            foreign_keys: vec![],
            indexes: vec![],
        }
    }

    #[test]
    fn postgres_create_table() {
        let gen = PostgresGenerator::new();
        let sql = gen
            .emit(&Operation::CreateTable { table: customer() })
            .unwrap();
        let joined = sql.join("\n");
        assert!(joined.contains("CREATE TABLE \"Customer\""));
        assert!(joined.contains("GENERATED BY DEFAULT AS IDENTITY"));
        assert!(joined.contains("character varying(200)"));
        assert!(joined.contains("PRIMARY KEY"));
    }

    #[test]
    fn sqlite_create_table() {
        let gen = SqliteGenerator::new();
        let sql = gen
            .emit(&Operation::CreateTable { table: customer() })
            .unwrap();
        let joined = sql.join("\n");
        assert!(joined.contains("CREATE TABLE \"Customer\""));
        assert!(joined.contains("PRIMARY KEY AUTOINCREMENT"));
        assert!(joined.contains("\"Name\" TEXT NOT NULL"));
    }

    #[test]
    fn sqlite_alter_column_no_soportado_aun() {
        let gen = SqliteGenerator::new();
        let op = Operation::AlterColumn {
            schema: None,
            table: "Customer".into(),
            new: name_col(),
            old: name_col(),
        };
        assert!(gen.emit(&op).is_err());
    }

    fn fk_op() -> Operation {
        use efrust_core::model::{ForeignKey, ReferentialAction};
        Operation::AddForeignKey {
            schema: None,
            table: "Order".into(),
            foreign_key: ForeignKey {
                name: "FK_Order_Customer".into(),
                columns: vec!["CustomerId".into()],
                principal_table: "Customer".into(),
                principal_schema: None,
                principal_columns: vec!["Id".into()],
                on_delete: ReferentialAction::Cascade,
            },
        }
    }

    fn index_op() -> Operation {
        use efrust_core::model::Index;
        Operation::CreateIndex {
            schema: None,
            table: "Order".into(),
            index: Index {
                name: "IX_Order_CustomerId".into(),
                columns: vec!["CustomerId".into()],
                is_unique: true,
                filter: None,
            },
        }
    }

    #[test]
    fn postgres_foreign_key_e_indice() {
        let gen = PostgresGenerator::new();
        let fk = gen.emit(&fk_op()).unwrap().join("\n");
        assert!(fk.contains(
            "ALTER TABLE \"Order\" ADD CONSTRAINT \"FK_Order_Customer\" \
             FOREIGN KEY (\"CustomerId\") REFERENCES \"Customer\" (\"Id\") ON DELETE CASCADE;"
        ));
        let ix = gen.emit(&index_op()).unwrap().join("\n");
        assert!(ix.contains("CREATE UNIQUE INDEX \"IX_Order_CustomerId\" ON \"Order\" (\"CustomerId\");"));
    }

    #[test]
    fn mysql_create_table_fk_indice() {
        let gen = MySqlGenerator::new();
        let create = gen.emit(&Operation::CreateTable { table: customer() }).unwrap().join("\n");
        assert!(create.contains("CREATE TABLE `Customer`"));
        assert!(create.contains("`Id` int NOT NULL AUTO_INCREMENT"));
        assert!(create.contains("`Name` varchar(200) NOT NULL"));
        assert!(create.contains("PRIMARY KEY (`Id`)"));

        let fk = gen.emit(&fk_op()).unwrap().join("\n");
        assert!(fk.contains(
            "ALTER TABLE `Order` ADD CONSTRAINT `FK_Order_Customer` \
             FOREIGN KEY (`CustomerId`) REFERENCES `Customer` (`Id`) ON DELETE CASCADE;"
        ));
        let ix = gen.emit(&index_op()).unwrap().join("\n");
        assert!(ix.contains("CREATE UNIQUE INDEX `IX_Order_CustomerId` ON `Order` (`CustomerId`);"));
    }

    #[test]
    fn sqlite_indice_si_fk_inline_en_create_table() {
        let gen = SqliteGenerator::new();
        // El índice se genera.
        let ix = gen.emit(&index_op()).unwrap().join("\n");
        assert!(ix.contains("CREATE UNIQUE INDEX \"IX_Order_CustomerId\" ON \"Order\" (\"CustomerId\");"));
        // La FK por ALTER se omite (sin sentencias): SQLite la declara inline.
        let fk = gen.emit(&fk_op()).unwrap();
        assert!(fk.is_empty(), "SQLite omite AddForeignKey (va inline en CREATE TABLE)");
    }

    #[test]
    fn sqlite_create_table_incluye_fk_inline() {
        use efrust_core::model::{ForeignKey, ReferentialAction};
        let mut order = customer();
        order.name = "Order".into();
        order.foreign_keys.push(ForeignKey {
            name: "FK_Order_Customer".into(),
            columns: vec!["Name".into()],
            principal_table: "Customer".into(),
            principal_schema: None,
            principal_columns: vec!["Id".into()],
            on_delete: ReferentialAction::Cascade,
        });
        let sql = SqliteGenerator::new()
            .emit(&Operation::CreateTable { table: order })
            .unwrap()
            .join("\n");
        assert!(sql.contains(
            "CONSTRAINT \"FK_Order_Customer\" FOREIGN KEY (\"Name\") \
             REFERENCES \"Customer\" (\"Id\") ON DELETE CASCADE"
        ));
    }

    #[test]
    fn sqlserver_genera_tsql() {
        let gen = SqlServerGenerator::new();
        let create = gen.emit(&Operation::CreateTable { table: customer() }).unwrap().join("\n");
        assert!(create.contains("CREATE TABLE [Customer]"));
        assert!(create.contains("[Id] int NOT NULL IDENTITY(1,1)"));
        assert!(create.contains("[Name] nvarchar(200) NOT NULL"));
        assert!(create.contains("CONSTRAINT [PK_Customer] PRIMARY KEY ([Id])"));

        let fk = gen.emit(&fk_op()).unwrap().join("\n");
        assert!(fk.contains(
            "ALTER TABLE [Order] ADD CONSTRAINT [FK_Order_Customer] \
             FOREIGN KEY ([CustomerId]) REFERENCES [Customer] ([Id]) ON DELETE CASCADE;"
        ));
    }
}
