//! Provider de PostgreSQL.

use efrust_core::diff::Operation;
use efrust_core::model::{Column, ForeignKey, Index, ReferentialAction, Table};

use crate::generator::{ProviderError, SqlGenerator};

/// Cláusula `ON DELETE` para una acción referencial (vacía para `NoAction`).
fn on_delete_clause(action: ReferentialAction) -> &'static str {
    match action {
        ReferentialAction::Cascade => " ON DELETE CASCADE",
        ReferentialAction::SetNull => " ON DELETE SET NULL",
        ReferentialAction::SetDefault => " ON DELETE SET DEFAULT",
        ReferentialAction::Restrict => " ON DELETE RESTRICT",
        ReferentialAction::NoAction => "",
    }
}

pub struct PostgresGenerator;

impl PostgresGenerator {
    pub fn new() -> Self {
        Self
    }

    fn qualified(&self, schema: Option<&str>, name: &str) -> String {
        match schema {
            Some(s) => format!("{}.{}", self.quote_ident(s), self.quote_ident(name)),
            None => self.quote_ident(name),
        }
    }

    /// Render de una columna dentro de `CREATE TABLE`.
    fn column_def(&self, column: &Column) -> Result<String, ProviderError> {
        let mut parts = vec![self.quote_ident(&column.name)];

        if column.is_identity {
            // PK autoincremental idiomática en Postgres moderno.
            parts.push("integer GENERATED BY DEFAULT AS IDENTITY".into());
        } else {
            parts.push(self.store_type_for(column)?);
        }

        if let Some(coll) = &column.collation {
            parts.push(format!("COLLATE {}", self.quote_ident(coll)));
        }
        if !column.is_nullable {
            parts.push("NOT NULL".into());
        }
        if let Some(def) = &column.default_value_sql {
            parts.push(format!("DEFAULT {def}"));
        }
        Ok(parts.join(" "))
    }

    fn create_table(&self, table: &Table) -> Result<String, ProviderError> {
        let mut lines: Vec<String> = Vec::new();
        for c in &table.columns {
            lines.push(format!("    {}", self.column_def(c)?));
        }
        if let Some(pk) = &table.primary_key {
            let cols: Vec<String> = pk.columns.iter().map(|c| self.quote_ident(c)).collect();
            lines.push(format!(
                "    CONSTRAINT {} PRIMARY KEY ({})",
                self.quote_ident(&pk.name),
                cols.join(", ")
            ));
        }
        Ok(format!(
            "CREATE TABLE {} (\n{}\n);",
            self.qualified(table.schema.as_deref(), &table.name),
            lines.join(",\n")
        ))
    }
}

impl Default for PostgresGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl SqlGenerator for PostgresGenerator {
    fn name(&self) -> &'static str {
        "postgres"
    }

    fn store_type_for(&self, column: &Column) -> Result<String, ProviderError> {
        if let Some(st) = &column.store_type {
            return Ok(st.clone());
        }
        let clr = column.clr_type.as_deref().unwrap_or("");
        let mapped = match clr {
            "System.Int16" => "smallint",
            "System.Int32" => "integer",
            "System.Int64" => "bigint",
            "System.Boolean" => "boolean",
            "System.Single" => "real",
            "System.Double" => "double precision",
            "System.Decimal" => "numeric",
            "System.DateTime" => "timestamp without time zone",
            "System.DateTimeOffset" => "timestamp with time zone",
            "System.Guid" => "uuid",
            "System.Byte[]" => "bytea",
            "System.String" => {
                return Ok(match column.max_length {
                    Some(n) if n > 0 => format!("character varying({n})"),
                    _ => "text".to_string(),
                });
            }
            _ => {
                return Err(ProviderError::UnmappedType {
                    clr: clr.to_string(),
                    column: column.name.clone(),
                })
            }
        };
        Ok(mapped.to_string())
    }

    fn emit(&self, op: &Operation) -> Result<Vec<String>, ProviderError> {
        let sql = match op {
            Operation::CreateTable { table } => vec![self.create_table(table)?],
            Operation::DropTable { schema, name } => {
                vec![format!("DROP TABLE {};", self.qualified(schema.as_deref(), name))]
            }
            Operation::AddColumn { schema, table, column } => vec![format!(
                "ALTER TABLE {} ADD COLUMN {};",
                self.qualified(schema.as_deref(), table),
                self.column_def(column)?
            )],
            Operation::DropColumn { schema, table, name } => vec![format!(
                "ALTER TABLE {} DROP COLUMN {};",
                self.qualified(schema.as_deref(), table),
                self.quote_ident(name)
            )],
            Operation::AlterColumn { schema, table, new, .. } => {
                let qt = self.qualified(schema.as_deref(), table);
                let qc = self.quote_ident(&new.name);
                let ty = self.store_type_for(new)?;
                let null = if new.is_nullable {
                    format!("ALTER COLUMN {qc} DROP NOT NULL")
                } else {
                    format!("ALTER COLUMN {qc} SET NOT NULL")
                };
                vec![
                    format!("ALTER TABLE {qt} ALTER COLUMN {qc} TYPE {ty};"),
                    format!("ALTER TABLE {qt} {null};"),
                ]
            }
            Operation::AddForeignKey { schema, table, foreign_key } => {
                vec![self.add_foreign_key(schema.as_deref(), table, foreign_key)]
            }
            Operation::DropForeignKey { schema, table, name } => vec![format!(
                "ALTER TABLE {} DROP CONSTRAINT {};",
                self.qualified(schema.as_deref(), table),
                self.quote_ident(name)
            )],
            Operation::CreateIndex { schema, table, index } => {
                vec![self.create_index(schema.as_deref(), table, index)]
            }
            Operation::DropIndex { schema, name, .. } => {
                // En Postgres los índices viven en el esquema de su tabla.
                vec![format!("DROP INDEX {};", self.qualified(schema.as_deref(), name))]
            }
        };
        Ok(sql)
    }
}

impl PostgresGenerator {
    fn add_foreign_key(&self, schema: Option<&str>, table: &str, fk: &ForeignKey) -> String {
        let cols: Vec<String> = fk.columns.iter().map(|c| self.quote_ident(c)).collect();
        let pcols: Vec<String> = fk.principal_columns.iter().map(|c| self.quote_ident(c)).collect();
        let principal = self.qualified(
            fk.principal_schema.as_deref().or(schema),
            &fk.principal_table,
        );
        format!(
            "ALTER TABLE {} ADD CONSTRAINT {} FOREIGN KEY ({}) REFERENCES {} ({}){};",
            self.qualified(schema, table),
            self.quote_ident(&fk.name),
            cols.join(", "),
            principal,
            pcols.join(", "),
            on_delete_clause(fk.on_delete),
        )
    }

    fn create_index(&self, schema: Option<&str>, table: &str, index: &Index) -> String {
        let unique = if index.is_unique { "UNIQUE " } else { "" };
        let cols: Vec<String> = index.columns.iter().map(|c| self.quote_ident(c)).collect();
        let filter = index
            .filter
            .as_ref()
            .map(|f| format!(" WHERE {f}"))
            .unwrap_or_default();
        format!(
            "CREATE {unique}INDEX {} ON {} ({}){filter};",
            self.quote_ident(&index.name),
            self.qualified(schema, table),
            cols.join(", "),
        )
    }
}
